# Generated by Django 6.0.6 on 2026-06-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('given_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('place_of_residence', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
